version: '3.8'

services:
  go-mongo-quickstart:
    build:
      context: .
      dockerfile: resources/docker/go/Dockerfile
    image: quay.io/${QUAY_USER_OR_ORG}/${IMAGE_NAME_WITHOUT_TAG}:${IMAGE_TAG}
    restart: always
    environment:
      DB_NAME: ${DB_NAME}
      DB_URL: ${DB_URL}
      SERVICE_BINDING_ROOT: ${SERVICE_BINDING_ROOT}
    container_name: ${CONTAINER_NAME}
    ports:
      - "8080:8080"
    depends_on:
      - mongo_db
    volumes:
      - ./test-bindings/bindings:/bindings

  mongo_db:
    image: mongo
    restart: always
    env_file:
      - resources/docker/mongo/.env
    container_name: mongo-test-db
    ports:
      - "27017:27017"
    volumes:
      # 1st one is for storing data outside the container. 2nd is for initializing the DB
      - /tmp/data/mongodb:/data/db
      - ./resources/docker/mongo/db-init/:/docker-entrypoint-initdb.d
